### PR TITLE
Add a zebra striped style

### PR DESCRIPTION
**Pull request by pat-pat-patrick**
Adjust background colors, based on colors using in system dark mode

Adjust the vertical-align method from bottom to center

image
image

### CODE REVIEW

**Comment by hazarek** [comment]
Table borders?, purple tones? #2E2D33. we don't live in the 90's. Amateurs leave the design to the experts.

**Comment by setanarut** [comment]
You spoiled the Apple colors I carefully selected. colors and contrast are bad. why purple? Look at this insufficient contrast. Numbers cannot be read.
cap
this is correct colors;
cap 1

you are amateur.

**Comment by pat-pat-patrick** [comment]
Hi @hazarek , thank you for your criticism. I changed the colors to match the standard of contrast ratio. How do you feel about it now?
[https://webaim.org/resources/contrastchecker/?fcolor=61ADFF&bcolor=1F1F1F](url)
image
time-text: #61ADFF
bg-color: #434443
bg-odd-color: #121212
bg-even-color: #1F1F1F

**Comment by pat-pat-patrick** [comment]
BTW, I indeed am an amateur. I am a doctor, not a designer, and I just started approaching CSS yesterday in my leisure time.

**Pull request merged**
