### PR TITLE
Add a zebra striped theme of dark-light

### PR DESCRIPTION
**Pull request by pat-pat-patrick**
Adjust background colors, based on colors using in system dark mode

Adjust the vertical-align method from bottom to center

image

### CODE REVIEW

**Comment by pat-pat-patrick** [comment]
The light mode needs some changes, I forgot to verify it.

**Comment by tattali** [comment]
Hi @CalvertDXie
Thank you for your contributions!

Can you do it directly on the initial darklight theme? thx!

**Comment by pat-pat-patrick** [comment]
Absolutely, it's my pleasure.

**Comment by setanarut** [comment]
Whats going on here? it looks very bad. I wrote style according to Apple [Human Interface Guidelines]. (https://developer.apple.com/design/human-interface-guidelines/macos/visual-design/dark-mode/). This looks amateur. a very disrespectful change.

**Pull request closed without merging**
